services:
  db:
    image: postgres:15
    container_name: rt-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - rt_pgdata:/var/lib/postgresql/data

  rt:
    build: .
    container_name: rt6
    depends_on:
      - db
    environment:
      RT_WEB_PORT: ${RT_WEB_PORT}
      RT_WEB_DOMAIN: ${RT_WEB_DOMAIN}
      RT_ORGANIZATION: ${RT_ORGANIZATION}
      RT_RTNAME: ${RT_RTNAME}
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${RT_WEB_PORT}:${RT_WEB_PORT}"
    volumes:
      - ./RT_SiteConfig.pm:/opt/rt6/etc/RT_SiteConfig.pm
      - ./env_file:.env

volumes:
  rt_pgdata:
