name: Build RT Docker Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Încarcă variabilele din fișierul .env (doar pentru workflow-ul acesta)
      RT_WEB_PORT: ${{ secrets.RT_WEB_PORT }}
      RT_WEB_DOMAIN: ${{ secrets.RT_WEB_DOMAIN }}
      RT_ORGANIZATION: ${{ secrets.RT_ORGANIZATION }}
      RT_RTNAME: ${{ secrets.RT_RTNAME }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build RT Docker image
        run: |
          docker build \
            --build-arg RT_WEB_PORT=${RT_WEB_PORT} \
            --build-arg RT_WEB_DOMAIN=${RT_WEB_DOMAIN} \
            --build-arg RT_ORGANIZATION=${RT_ORGANIZATION} \
            --build-arg RT_RTNAME=${RT_RTNAME} \
            --build-arg POSTGRES_HOST=${POSTGRES_HOST} \
            --build-arg POSTGRES_USER=${POSTGRES_USER} \
            --build-arg POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
            --build-arg POSTGRES_DB=${POSTGRES_DB} \
            -t rt6:latest .

      - name: List local Docker images
        run: docker images
